import { generalSans } from "@/assets/fonts";
import "./globals.css";
import { cn } from "@/util";
import Providers from "./providers";
import Images from "./images";

export const metadata = {
  title: {
    template: "Captivate – %s",
    default: "Captivate",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Images />
      </head>
      <body
        className={cn(
          generalSans.variable,
          "font-sans antialiased bg-background text-foreground w-screen",
        )}
      >
        <Providers attribute="class" disableTransitionOnChange>
          {children}
        </Providers>
      </body>
    </html>
  );
}
