import { generalSans } from "./_assets/fonts";

import "./_assets/globals.css";

import { cn } from "@/util/cn";
import { Toaster } from "@/components/toaster";

import Images from "./_assets/images";
import Providers from "./providers";

export const metadata = {
  title: {
    template: "Captivate – %s",
    default: "Captivate",
  },
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Images />
      </head>
      <body
        className={cn(
          generalSans.variable,
          "font-sans antialiased bg-background text-foreground w-screen"
        )}
      >
        <Providers attribute="class" disableTransitionOnChange>
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
